### ISSUE TITLE
Forged in Fire 

### ISSUE THREAD

**Issue by Logical-King** [Zydrax/Baldazzar-BUG-Traker#14]
[https://www.wowhead.com/quest=39683/forged-in-fire](url)

![Screenshot_22](https://user-images.githubusercontent.com/98852534/157632587-73259a50-d3c4-4294-845b-c334d2a0772b.png)

Objective do not give credit when credit is due. haha.

**Comment by Thordekk** [comment]
Issue fixed, improved health of npc and now u obtain the creditt  perfect
