### ISSUE TITLE
Cannot queue up for Shadowlands dungeons

### ISSUE THREAD

**Issue by mutulik** [Zydrax/Baldazzar-BUG-Traker#147]
Shadowlands dungeons only accept one level to enter. and that is the entry level
![Screenshot 2022-11-03 124355](https://user-images.githubusercontent.com/64900987/199723499-befa516b-0690-46d8-a922-f244b81d3948.png)

**Comment by mutulik** [comment]
![Screenshot 2022-11-03 124537](https://user-images.githubusercontent.com/64900987/199723934-e9dd3d54-5125-4eb7-bf19-bd48cd4a05b2.png)
![image](https://user-images.githubusercontent.com/64900987/199723966-be8adf19-77de-4950-9f3c-91c47dfaf542.png)

**Comment by Thordekk** [comment]
ure correct need change access requirements
