### ISSUE TITLE
7.35 Problem

### ISSUE THREAD

**Issue by ooinini** [Zydrax/Baldazzar-BUG-Traker#153]
Need some help! Please. 7.35Legion. There are some problems with my server. When the number of players reaches "100", they will be drop. This "100" is not a fixed value. It can reach 128 people at most. I looked up my source code and didn't find the value of the number limit. I also tried to modify the number of threads in worldconfig, but it didn't work.
![2](https://user-images.githubusercontent.com/94303475/214999395-593d4505-6fd6-4cb2-8faf-c373bd87a4f6.png)
Where can i fix it?

**Comment by NumboWoW** [comment]
For help with own server problems make a issue on the github from the source you have.

**Comment by ooinini** [comment]
Baldazzar-core!!!

**Comment by NumboWoW** [comment]
We never published our source

**Comment by NumboWoW** [comment]
Got source from DekkCore? It is a partner project but still not our source

**Comment by ooinini** [comment]
No.I forgot.but i'm sure it's Baldazzar-core

**Comment by ooinini** [comment]
!
![3](https://user-images.githubusercontent.com/94303475/215103366-fe0510e8-5d3a-4bb3-9e88-48b8c97fbbe2.png)

**Comment by Gyarakushii** [comment]
Where did you get it??

**Comment by ooinini** [comment]
Someone bought it and gave it to me .but i can't find him anymore.

**Comment by Gyarakushii** [comment]
Do you remember his name?

**Comment by NumboWoW** [comment]
Show me the Banner.cpp and src->server->worldserver->main.cpp, i still dont believe its baldazzar

**Comment by ooinini** [comment]
No.It was at least about half a year

**Comment by ooinini** [comment]
i'll show you anything.But can my problem be solved T T

**Comment by NumboWoW** [comment]
![image](https://user-images.githubusercontent.com/101930210/215106109-0b0ad7f1-024b-4c23-8520-f014c099d8d6.png)

Closed, thanks
