### ISSUE TITLE
Enha shaman artifact quest not working

### ISSUE THREAD

**Issue by TristanimBambusovic** [Zydrax/Baldazzar-BUG-Traker#22]
The Hammer In The Deep(40224) is not working,after picking up Doomhammer the quest is not completed.. i got the artifact but not being able to complete this quest makes a lot of order hall stuff impossible to complete,for example achievment that´s required for Legion Pathfinder, Artifact Appereance, Order Hall Campaign etc..

**Comment by NumboWoW** [comment]
![image](https://user-images.githubusercontent.com/101930210/160707713-7c8bdf2a-4154-423e-84db-573545f9776b.png)

I could do it..
If you still have the problem then please contact a gm on discord or directly ingame :)
