### ISSUE TITLE
Deliverance Point - Missing Flight Master

### ISSUE THREAD

**Issue by Omentep** [Zydrax/Baldazzar-BUG-Traker#40]
Missing the flight master in Deliverance Point Horde. (Not sure if Alliance is missing.)

Edit - Could be a phasing issue.

**Comment by NumboWoW** [comment]
do you made the legionfall intro ?

**Comment by NumboWoW** [comment]
![image](https://user-images.githubusercontent.com/101930210/160502684-2a4b58c1-72ba-4db5-b82f-e660b5a7c507.png)

Should be there after the intro.
Sadly legion has 3, but maybe we can skip them in future ;)

**Comment by Omentep** [comment]
Yeah they are there after the legion intro, however the flight path is not there before that so way the server is set up you can fly there but cannot anywhere else before completing the intro essentially stranding the player in a phase with no flight masters.
