### ISSUE TITLE
Quest - The Tranquil Forest

### ISSUE THREAD

**Issue by Omentep** [Zydrax/Baldazzar-BUG-Traker#41]
https://www.wowhead.com/quest=39731/the-tranquil-forest

Issue: Once accepted from the scouting map to begin [Val'sharah] quest line, quest has a step to - Travel to Dalaran which never gets checked off/completed.

**Comment by NumboWoW** [comment]
![image](https://user-images.githubusercontent.com/101930210/160383815-ecdf23a9-1601-4148-9dce-513e0cccc45e.png)

For me the "travel to dala" part got finished right after I go to Khadgar at Krasus' Landing.
There is a known bug that you can only make 1 scout map "travel to dala" at a time.
So dont accept all 4 zones at once, do them one after another and try again please.

**Comment by Omentep** [comment]
Ok i'll give that a shot.
