### ISSUE TITLE
Quest To Old Friends

### ISSUE THREAD

**Issue by Omentep** [Zydrax/Baldazzar-BUG-Traker#51]
https://www.wowhead.com/quest=38582/to-old-friends

Entering the cave does not update the quest objective, npc that is the kill objective once that happens summons a dozen or more hostiles that can effectively 3 shot any leveling player.

**Comment by Omentep** [comment]
You don't stand a chance against that npc, like I said he summons at least a dozen npc followers and they deleted me I understand there's a scaling issue but maybe removing the spell he uses to summon them is a good option if possible.

**Comment by NumboWoW** [comment]
![image](https://user-images.githubusercontent.com/101930210/160918806-43f84c4f-c267-483f-bec6-18df2bf8d364.png)
Alr! Sry... 

was long awake and only cared about the quest dont update part^^

**Comment by NumboWoW** [comment]
Should be doable now
