### ISSUE TITLE
Guild Herald

### ISSUE THREAD

**Issue by Omentep** [Zydrax/Baldazzar-BUG-Traker#69]
I have the Alliance and the Horde Guild Herald pets. 

On my Orc Warlock I cannot summon either one, tooltips for them both state - "You are not the right faction for this companion". The only explanation I can think of is maybe they're not usable on characters that are not in a guild which makes sense but I don't know.

![image](https://user-images.githubusercontent.com/102278715/161866900-eec1d78a-b72e-4d71-952c-1734f9c2602a.png)

![image](https://user-images.githubusercontent.com/102278715/161866919-8e51eac1-3b87-4dae-bd48-b914c9c61b57.png)

**Comment by NumboWoW** [comment]
You need to be in a guild and at least friendly :)
