### ISSUE TITLE
The Emerald Nightmare: Il'gynoth can´t turn in

### ISSUE THREAD

**Issue by TristanimBambusovic** [Zydrax/Baldazzar-BUG-Traker#71]
After completing the quest The Emerald Nightmare: Il'gynoth(43548) as SHAMAN  i can´t turn it in and get my reward because the quest is not visible at the npc.. for shaman its Advisor Sevel (96746)
![bug](https://user-images.githubusercontent.com/101489504/162085061-f7d7a379-eb64-41d8-aa57-a6a170486c77.jpg)
![bugľ](https://user-images.githubusercontent.com/101489504/162085074-8fd008a6-28af-4122-a0f6-8aaea3d3187f.jpg)

**Comment by TristanimBambusovic** [comment]
It´s possible that the same bug will occur for simmiliar quest´s for example there´s the exact same quest that sends players to kill Xavius,Ursoc or Gul´dan :)

**Comment by NumboWoW** [comment]
this quest is fixed, may I ask you to open another report if you find the others quests are bugged too ?
