### ISSUE TITLE
Quest "Queen-Sized Troubles" (24501) Shows wrong quest location. /by Gyarakushi

### ISSUE THREAD

**Issue by Zydrax** [Zydrax/Baldazzar-BUG-Traker#9]
Quest "Queen-Sized Troubles" (24501) Shows wrong quest location.
Where it should be (red) vs where it is (blue):
https://cdn.discordapp.com/attachments/929701807708602408/940679843585085501/unknown.png

https://www.wowhead.com/quest=24501/queen-sized-troubles

**Comment by Thordekk** [comment]
i cant see the image
