### ISSUE TITLE
Quest: Candle of Command

### ISSUE THREAD

**Issue by alex4e09** [Zydrax/Baldazzar-BUG-Traker#99]
After taking it and abandoning my character become unable to move forward or backward nor jumping.
![unknown](https://user-images.githubusercontent.com/104902101/166670143-92314cbb-d0e3-4ed1-8e4b-d8babc35b7f2.png)

after several minutes the only workaround i found was using ingame:  ESC >> Help >> Character Stuck >> Teleport to Graveyard

Hearthstone
.unstuck
website teleport hub
Dalaran Hearthstone
Fligh Master Whistle
( Non of these worked )

**Comment by NumboWoW** [comment]
I could walk again after like 30sec but still the questline is kinda bug

**Comment by NumboWoW** [comment]
![image](https://user-images.githubusercontent.com/101930210/167323380-1cf686bf-a6da-468f-b4f0-2fb8cd3cd593.png)

Random cant move and dont go away xd

**Comment by NumboWoW** [comment]
Teleport to Graveyard really do the trick after that, still bad bug
